name: PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Discord
      uses: Ilshidur/action-discord@v2
      with:
        webhook: ${{ secrets.WEBHOOK_URL }}
        content: 'A new pull request has been created: ${{ github.event.pull_request.html_url }}'
        username: 'GitHub Notification Bot'
      env:
        WEBHOOK_URL: <https://discord.com/api/webhooks/1186058910868721664/MMBDC6WUedMXyDP36qMUXlwdD6Azi5Iy85nbVwjmYxM_imxtAxw1ykQp1gQszzkfrMx2>
